### PR TITLE
Update readme, as we are installing more sets

### PR DESCRIPTION
**Pull request by ZhanYF**
I forget to update readme in #4, let's do it now :)

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
It still mentions that X is not installed higher up in the readme.

**Comment by ZhanYF** [comment]
updated.

**Comment by ZhanYF** [comment]
P.S. could you make a release for this repository so that https://github.com/cross-platform-actions/action can use the new images?

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
> P.S. could you make a release for this repository so that https://github.com/cross-platform-actions/action can use the new images?

Will do.

**Comment by jacob-carlborg** [comment]
I've pushed a tag and waiting for the CI pipeline to complete. I need to make a small change in the action repository and a new release there as well.

**Comment by jacob-carlborg** [comment]
I apologize for the delay, but I've published a new release now: [v0.2.0](https://github.com/cross-platform-actions/action/releases/tag/v0.2.0).

**Pull request merged**
