### PR TITLE
Openbsd71 stable

### PR DESCRIPTION
**Pull request by ghost**
similar to https://github.com/cross-platform-actions/openbsd-builder/pull/3 but adds 7.1 stable

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
I've run the build three times, it fails to SSH to the VM and cannot provision it. Have you built the image locally?

**Comment by ghost** [comment]
i cant figure out how to run the build on fedora. the `cocoa` display type isnt valid and if i change it to `gtk` then i get an error about missing bios in the resources dir. the readme wasnt clear on prereqs or other assumptions needed to run it.

can i get some help with this please? 6.9 isnt supported upstream anymore.

**Comment by jacob-carlborg** [comment]
> the cocoa display type isnt valid and if i change it to gtk

I've updated the readme to mention that the `display` variable needs to be overridden on non-macOS platforms.

> then i get an error about missing bios in the resources dir

On Fedora, you need to install `edk2-ovmf` package. Then copy the installed `OVMF.fd` file (wherever it's located) to `resources/ovmf.fd`. I've updated the readme for this as well [1]. 

[1] https://github.com/cross-platform-actions/openbsd-builder/#uefi-firmware

**Comment by jacob-carlborg** [comment]
I tried running this locally and the problem is that the `dhclient` command is not available, which is used before starting the installation: https://github.com/cross-platform-actions/openbsd-builder/blob/8b12f7574548f2e8933f38fcb5a718670fd52a92/openbsd.pkr.hcl#L145. I'll see if I can find an alternative, or if you're more familiar with OpenBSD and know of another way.

**Comment by ghost** [comment]
it look to also fail on `S` prior to `dhclient`, and `ftp` afterwards. i tried with the 6.9 `miniroot.img` and i dont think its openbsd specific. maybe a change in the bios or something used by packer and its not actually loading the img before trying to do anything. but i dont know much about packer. as far as i can tell its stuck in the efi shell, not interacting with the os boot process at all, which may be why no commands work.

i tried to switch to using an iso instead (arm64 doesnt have an iso) and this also didnt work for me. i also checked a manual install vm and `/sbin/dhclient` does exist.

**Comment by jacob-carlborg** [comment]
> it look to also fail on S prior to dhclient

Not for me. 

> i tried with the 6.9 miniroot.img and i dont think its openbsd specific. maybe a change in the bios or something used by packer and its not actually loading the img before trying to do anything. but i dont know much about packer. as far as i can tell its stuck in the efi shell, not interacting with the os boot process at all, which may be why no commands work.

Oh, perhaps you have a newer version of the UEFI firmware, or something like that.

> i also checked a manual install vm and /sbin/dhclient does exist.

No, not in the shell which is available before installing:

Screen Shot 2022-05-30 at 07 33 24

I found out that these two commands work instead of `dhclient`:

```
"ifconfig em0 group dhcp<enter><wait>",
"ifconfig em0 inet autoconf<enter><wait>",
```

But these commands don't work for 6.9, so Packer need to somehow look at the current version and pick the right commands. Also after installing using these two commands it fails to SSH to the VM to do the final provisioning. I found this other Packer configuration file which installs OpenBSD 7.x [1], which might be of help.

[1] https://github.com/lavabit/robox/blob/dca342014f8bfd2d4e710eeafe7ebbe1f6163d70/generic-libvirt.json#L5491

**Comment by ghost** [comment]
given openbsd doesnt really support anything but the newest release is it fine to just drop the old versions and keep things current here? might make troubleshooting easier keeping everything updated

`uname -r` should get you the version (6.9, 7.1, etc) and could be used for a conditional.

**Comment by jacob-carlborg** [comment]
I've tried building the image locally and installing OpenBSD works, but when it reboots it cannot boot, it hangs here:
Screen Shot 2022-06-03 at 20 40 46

**Comment by jacob-carlborg** [comment]
This is now fixed: https://github.com/cross-platform-actions/openbsd-builder/releases/tag/v0.3.0. I'll update the GitHub action shortly.

**Comment by ghost** [comment]
what ended up being the fix for this? seems like there was a similar commit but not sure how it worked different.

**Comment by jacob-carlborg** [comment]
> what ended up being the fix for this? seems like there was a similar commit but not sure how it worked different.

@portno12 right, forgot to mention that here. I split up the changes across multiple commits. The main thing that solved the problem was to update to a later version of the UEFI firmware: https://github.com/cross-platform-actions/openbsd-builder/commit/6670ab93f9d01604306e26f432213c99740ad766. When the firmware was updated it also required to change the disk devices: https://github.com/cross-platform-actions/openbsd-builder/commit/26a9177e50413a229a74b3bb439c58a0ac72952b. To support both OpenBSD 7.x and 6.x, I extracted the DHCP boot commands to a variable: https://github.com/cross-platform-actions/openbsd-builder/commit/d5de77ef0af17392b89128c24994b13d8ddc76d2.

**Comment by jacob-carlborg** [comment]
I apologize for the delay, but I created a new release of the GitHub action now: https://github.com/cross-platform-actions/action/releases/tag/v0.6.0. You need to update to 0.6.0 to use OpenBSD 7.1.

**Pull request closed without merging**
